### PR TITLE
Swipe retry

### PR DESCRIPTION
**Pull request by shrutiagarwal28**

### CODE REVIEW

**Review by gururaj3 — COMMENTED** [review]
@shrutiagarwal28

1. Why is the file "accounts/static/accounts/style.css" changed? It has a lot of code currently. 

2. Why are these 2 files added, it doesn't have anything related to code: 
      1. accounts/templates/accounts/swiper.js
      2. accounts/templates/accounts/base2.html

3. I also see there are some UI changes. Can you please upload a pic showing the updated UI?

**Comment by shrutiagarwal28** [comment]
@gururaj3 
1. Style.css has fff colors changed to FFFF, making things whiter, that's all.
2. I need the swiper.js and base2.html for testing the added functions before I integrate them. Will disconnect and delete them once the enhancement is fully integrated.
3. The css changes don't cause any visible change to the UI. Discussed these with Ben about making things whiter

**Comment by gururaj3** [comment]
@shrutiagarwal28 -
I think we should not add any files that are meant for testing. I think it would be good if we remove those 2 files because it is our staging and eventually will be pushed to production. 

@benji7890 -
Can you review the UI changes and if everything looks good, please approve the PR.

**Review by benji7890 — APPROVED** [review]

**Comment by shrutiagarwal28** [comment]
@gururaj3 yeah, but I'll be anyway deleting these files in a future commit.

**Comment by gururaj3** [comment]
@shrutiagarwal28 

I am approving the PR and you can go ahead and merge it. 

But I am going to make it clear that we should not be adding any testing related files to staging and production. Any testing related work is done on the personal branches/ dev and after everything is working as expected - then we go and create a PR for staging and production.

**Review by gururaj3 — APPROVED** [review]
@shrutiagarwal28

I am approving the PR and you can go ahead and merge it.

But I am going to make it clear that we should not be adding any testing related files to staging and production. Any testing related work is done on the personal branches/ dev and after everything is working as expected - then we go and create a PR for staging and production.

**Comment by shrutiagarwal28** [comment]
> @shrutiagarwal28
> 
> I am approving the PR and you can go ahead and merge it.
> 
> But I am going to make it clear that we should not be adding any testing related files to staging and production. Any testing related work is done on the personal branches/ dev and after everything is working as expected - then we go and create a PR for staging and production.

@gururaj3 yeah, of course. Since this is partly completed I wanted it to be there; I'll definitely be deleting the replica files as soon as we have the completed functionality. Thanks.

**Pull request merged**
